buloneria/urls.py
from django.contrib import admin
from django.urls import path
from stock import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('stock/', views.stock, name='stock'),
    path('stock/nuevo/', views.nuevo, name='nuevo'),
    path('stock/eliminar/<int:id>/', views.eliminar, name='eliminar'),
    path('stock/actualizar/<int:id>/', views.actualizar, name='actualizar'),
    path('buscar/', views.buscar, name='buscar'),
    path('presupuestar/', views.presupuestar, name='presupuestar')

]

stock/models.py
from django.db import models

# Create your models here.
class Utilidad(models.Model):
    utilValor = models.FloatField()
    utilDescripcion = models.CharField(max_length = 100)
    def __str__ (self):
        return str(self.utilValor)
    
class Categorias (models.Model):
    catNom = models.CharField(max_length = 50)
    catDescripcion= models.CharField(max_length=100)
    def __str__(self):
        return self.catNom
    
class Marcas(models.Model):
    marcaNom = models.CharField(max_length = 50)
    marcaDescripcion= models.CharField(max_length=100)
    def __str__(self):
        return self.marcaNom
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marcas, on_delete=models.CASCADE)
    codigo = models.IntegerField()
    descripcion = models.CharField(max_length = 150)
    cantidad = models.IntegerField()
    precioCosto = models.FloatField(default=0.0)
    utilidad = models.ForeignKey(Utilidad, on_delete=models.CASCADE)
    precioPublico= models.FloatField(default=0.0)

def __str__(self):
        return self.title +'-by '+ self.user.username #muestra el titulo de la tarea en la administracion de django

stock/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto
class NuevoForm(ModelForm):
    class Meta:
        model= Producto
        fields=('codigo', 'categoria' , 'marca' , 'descripcion' , 'cantidad' , 'utilidad' , 'precioCosto' )
        widgets ={
            'codigo': forms.NumberInput(attrs={'class': 'form-control','id':'codigo','style': 'width: 150px'}),
            'categoria': forms.Select(attrs={'class': 'form-select','style': 'width: 220px'}),
            'marca': forms.Select(attrs={'class': 'form-select','id':'marca','style': 'width: 220px'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control', 'id':'descripcion','style': 'width: 500px'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control','id':'cantidad','style': 'width: 150px'}),
            'utilidad': forms.Select(attrs={'class': 'form-select','style': 'width: 220px'}),
            'precioCosto': forms.NumberInput(attrs={'class': 'form-control','style': 'width: 150px'}),
        }
        labels = {
            'precioCosto': 'Precio Costo',
        }
    def __init__(self, *args, **kwargs):
        super(NuevoForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].empty_label = 'Seleccione la categoría'
        self.fields['marca'].empty_label = 'Seleccione la marca'
        self.fields['utilidad'].empty_label = 'Seleccione la utilidad'


class ProductoForm(ModelForm):
    class Meta:
        model= Producto
        fields=('codigo', 'categoria' , 'marca' , 'descripcion' , 'cantidad' , 'utilidad' ,'precioCosto')
        widgets ={
            'codigo': forms.NumberInput(attrs={'class': 'form-control','id':'codigo','style': 'width: 150px'}),
            'categoria': forms.Select(attrs={'class': 'form-select','style': 'width: 150px','placeholder': 'Seleccione la categoría'}),
            'marca': forms.Select(attrs={'class': 'form-select','id':'marca','style': 'width: 150px','placeholder': 'Seleccione la marca'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control', 'id':'descripcion','style': 'width: 500px'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control','id':'cantidad','style': 'width: 150px'}),
            'utilidad': forms.Select(attrs={'class': 'form-select','style': 'width: 150px','placeholder': 'Seleccione la utilidad'}),     
            'precioCosto': forms.NumberInput(attrs={'class': 'form-select','style': 'width: 150px'}),            
        }
        labels = {
            'precioCosto': 'Precio Costo',
        }
            
class ProductoBusqueda(forms.Form):
    descripcion = forms.CharField(
        max_length=50,
        label= '',
        widget=forms.TextInput(attrs={'class': 'form-control-outline','style': 'width: 300px;','placeholder':'Ingrese la Busqueda'})
    )

stock/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from .models import Producto
from .forms import NuevoForm, ProductoForm, ProductoBusqueda
from django.template.defaultfilters import floatformat
from django.db.models import Q
# Create your views here.

def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == "GET":
        print('Enviando Formulario')
        return render(request, 'signup.html', {
        'form': UserCreationForm
        })

    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('stock')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    "error": 'Usuario ya Existe'
                })
        return render(request, 'signup.html', {
        'form': UserCreationForm,
        "error": 'Password no Coincide'
        })

#def stock(request):
#    return render(request,'stock.html')

def signout(request):
    logout(request)
    return redirect ('home')

def signin(request):
    if request.method == "GET":
        return render(request, 'signin.html', {
            'form': AuthenticationForm
        })
    else:
        print(request.POST)
        user=authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {
                'form': AuthenticationForm,
                'error': 'Usuario o password es Incorrecto'
            })
        else: 
            login(request, user)
            return redirect('stock')
        
@login_required 
def nuevo(request):
    if request.method=='GET':
        return render(request, 'nuevo.html',{
            'form': NuevoForm
        })
    else:
        form = NuevoForm(request.POST)
        if form.is_valid():
            form.save()  # Esto guarda los datos en la base de datos
            print(request.POST)
            return render(request, 'nuevo.html',{
                'form': NuevoForm
            })
@login_required 
def eliminar(request, id):
    producto = get_object_or_404 (Producto, id=id)
    producto.delete()
    return redirect('stock')

@login_required     
def actualizar(request, id):
    producto = get_object_or_404 (Producto, id=id)
    if request.method=='GET':
        form = ProductoForm(instance=producto)
        return render(request, 'actualizar.html',{
            'form': form,
            'producto': producto
        })
    elif request.method=='POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()  # Esto guarda los datos en la base de datos
            print(request.POST)
            return redirect('stock')
    else:
        return render(request, 'actualizar.html', {'form': None, 'producto': None})
    

#def buscar(request):
#    form = ProductoBusqueda()
#    return render(request, 'stock.html', {'form': form})
@login_required
def stock(request):
    form = ProductoBusqueda()
    if request.method == 'GET': 
        print('va el GET')
        productos = Producto.objects.all()
        for producto in productos:
            producto.precioPublico= floatformat(producto.precioCosto*producto.utilidad.utilValor,2)
        return render(request, 'stock.html', {
            'form': form,
            'productos': productos
            })

def buscar(request):
    if request.method=='POST':
        form=ProductoBusqueda(request.POST)
        print(request.POST)
        if form.is_valid():
            descripcion = form.cleaned_data['descripcion']
            print(f'EL VALOR DE DESCRIPCIONES: {descripcion}') #IMPRESION DE AYUDA
            palabrasClave= descripcion.split()
            print(palabrasClave)  #IMPRESION DE AYUDA
            palabrasClave=[Q(descripcion__icontains=palabra) for palabra in palabrasClave]
            productos = Producto.objects.filter(*palabrasClave)
            for producto in productos:
                producto.precioPublico= floatformat(producto.precioCosto*producto.utilidad.utilValor,2)
            return render(request, 'stock.html', {
                'form': form, 
                'productos': productos
                })
            
@login_required
def presupuestar(request):
    form = ProductoBusqueda()
    if request.method == 'GET': 
        print('va el GET')
        productos = Producto.objects.all()
        for producto in productos:
            producto.precioPublico= floatformat(producto.precioCosto*producto.utilidad.utilValor,2)
        return render(request, 'presupuesto.html', {
            'form': form,
            'productos': productos
            })

stock/templates/actualizar.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<!--<link rel="stylesheet" href="{% static '/css/nuevo.css' %}">-->
<div class="container">
    <div><h2>ACTUALIZAR PRODUCTO</h2></div>
    <form method="POST" action="{% url 'actualizar' id=producto.id %}">
        {%csrf_token%}
        {{ form.as_p }}
        <button class="btn btn-success">
            GUARDAR
        </button>    
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

stock/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>WAFER SAS CRUD</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">HOME</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/logout">LOGOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/stock">WAFE SAS STOCK</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/presupuestar">GENERAR PRESUPUESTO</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/signup">REGISTRARSE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/signin">LOGIN</a>
                </li>
                {%endif%}
                <!--<li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>-->
            </ul>
        </div>
    </div>
</nav>
<br>
<body>
    {% block content %} {% endblock %}
</body>

</html>

stock/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>HOME</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis modi animi quos voluptatibus! Laboriosam soluta, quam praesentium, iste assumenda reiciendis fugit minus aliquid quidem distinctio consequuntur, suscipit vel voluptas ea quasi enim. Quaerat
    modi assumenda quasi alias sapiente nisi reiciendis deserunt atque eum veniam, expedita repellendus ex laboriosam dolores suscipit magni eos nobis minima blanditiis ab. Laudantium animi cupiditate nemo placeat est accusamus sequi pariatur doloribus
    voluptates reiciendis, libero nisi eveniet id culpa aliquam asperiores quidem, dolorem ab recusandae quos doloremque ullam. Qui suscipit ullam nemo ut, dolorum eos molestiae quis inventore velit, nihil fuga alias rem quo reprehenderit, facilis deserunt
    laboriosam eius adipisci! Eaque, consequatur. Nulla modi veritatis expedita delectus ratione incidunt sunt amet cumque, quos pariatur maxime similique dignissimos quaerat nemo accusantium maiores, beatae aut harum illum officia at! Debitis aperiam
    accusantium voluptatem laboriosam vel tempora officiis facilis dolorum nihil laborum, temporibus aspernatur, distinctio obcaecati a. Incidunt tempore minus sunt architecto a numquam reiciendis dolorem obcaecati qui? Magnam, modi culpa. Pariatur quo
    cumque itaque cupiditate sequi maxime quisquam atque dicta esse ab delectus accusantium, ipsam nemo ducimus praesentium exercitationem eum dolor assumenda deserunt tempora quaerat molestias. Similique sed eligendi quos architecto autem, et reiciendis
    sit rerum dicta quasi.</p>
{% endblock %}

stock/templates/nuevo.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<!--<link rel="stylesheet" href="{% static '/css/nuevo.css' %}">-->
<div class="container">
    <div><h2>ALTA DE PRODUCTO</h2></div>
    <form method="POST" action="/stock/nuevo/">
        {%csrf_token%}
        {{ form}}
        <br>
        <button class="btn btn-success">
            GUARDAR
        </button>    
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

stock/templates/nuevo1.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/nuevo.css' %}">
<div class="container">
    <div><h2>ALTA DE PRODUCTO</h2></div>
    <div class="formulario">
        <form id="app" method="POST" action="/stock/nuevo/">
            {%csrf_token%}
            <div class="input-group mb-3">
                <!--<label>CATEGORIA: </label>&nbsp;<input type="text" id="id_categoria" name="id_categoria">-->
                <label class="input-group-text" for="inputGroupSelect01">CATEGORIA: </label>
                <select name="catNombre" id="id_categoria" class="form-select" id="inputGroupSelect01">
                    {% for catnombre in catnombre %}
                    <option value='{{catnombre.catNombre}}'>{{catnombre.catNombre}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">MARCA</span>
                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="marca" id="codigo">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">CODIGO</span>
                <input type="numeric" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="codigo" id="codigo">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">DESCRIPCION</span>
                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="descripcion" id="descripcion">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">CANTIDAD</span>
                <input type="numeric" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="cantidad" id="cantidad">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">PRECIO COSTO</span>
                <input type="numeric" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="precioUnit" id="precioUnit">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">UTILIDAD</span>
                <input type="numeric" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="utilidad" id="precioUnit">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">PRECIO PUBLICO</span>
                <input type="numeric" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="precioVPublico" id="precioVPublico">
            </div>
            <div class="botonera">
                <button type="submit" class="btn btn-success">
                        GUARDAR
                    </button>
                <a href="" class="btn btn-danger">CANCELAR</a>
            </div>
        </form>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

stock/templates/presupuesto.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/stock.css' %}">



<div class="container">
    <div class="row">
        <div class="col-12"><h3>PRESUPUESTO</h3></div>
    </div>
    <div class="row">
        <div class="col-md-6 d-flex align-items-center" style="background-color:  #e3e3e3; padding: 5px;">
                <form class="d-flex align-items-center" method="post" action="{% url 'buscar' %}" style="padding: 5px;" >
                    {%csrf_token%}
                    <div class="d-flex align-items-center justify-content-center"style="padding: 5px;" >
                        {{ form }}
                    </div>
                    <div style="padding: 5px;">
                        <button type="submit" class="btn btn-warning" >BUSCAR</button>
                    </div>
                </form>
        </div>
        <div class="col-md-6 d-flex align-items-center" style="background-color: #e3e3e3; padding: 5px; " >
            <div style=" padding: 5px;">
                <a class="btn btn-success" href="{% url 'nuevo' %}">NUEVO</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col" style="background-color: #e3e3e3; padding: 5px;">
            <div class="table-responsive"> 
                <form action="">
                    {%csrf_token%}
                    <table id="tabla" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr class="encabezados">
                                <th scope="col">ID</th>
                                <th scope="col">CATEG</th>
                                <th scope="col">MARCA</th>
                                <th scope="col">CODIGO</th>
                                <th scope="col">DESCRIPCION</th>
                                <th scope="col">CANTIDAD</th>
                                <th scope="col">P COSTO</th>
                                <th scope="col">UTLIDAD</th>
                                <th scope="col">P VENTA</th>
                                <th scope="col">ACCIONES</th>
                                <!-- Agrega más columnas según las propiedades de tu modelo Producto -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for producto in productos %}
                                <tr class="contenido">
                                    <td scope="row" class="columNum">{{ producto.id }}</td>
                                    <td class="columCategoria">{{ producto.categoria.catNom }}</td>
                                    <td class="columMarca">{{ producto.marca.marcaNom }}</td>
                                    <td class="columNum">{{ producto.codigo }}</td>
                                    <td class="columDescripcion">{{ producto.descripcion }}</td>
                                    <td class="columNum">{{ producto.cantidad }}</td>
                                    <td class="columMoneda">${{ producto.precioCosto }}</td>
                                    <td class="columUtilidad">{{ producto.utilidad.utilDescripcion}}</td>
                                    <td class="columMoneda">${{ producto.precioPublico}}</td>
                                    <td class="centrarbotones">
                                        <div>   
                                            <a class="btn btn-primary btn-sm " href="{% url 'actualizar' id=producto.id %}">EDITAR</a>
                                            <a class="btn btn-danger btn-sm" href="{% url 'eliminar' id=producto.id %}">ELIMINAR</a>
                                        </div>
                                    </td>
                                    <!-- Agrega más celdas según las propiedades de tu modelo Producto -->
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
        
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

stock/templates/signin.html
{% extends 'base.html' %} {% block content %}
<h1>Login</h1>
{{error}}
<form action="/signin/" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button>
        Signin
    </button>
    
</form>
{% endblock %}

stock/templates/signup.html
{% extends 'base.html' %} {% block content %}
<h1>Signup</h1>
{{error}}
<form action="/signup/" method="POST">
    {%csrf_token%} {{form.as_p}}
    <button>
            Signup
    </button>
</form>
{% endblock %}

stock/templates/stock copy.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/stock.css' %}">



<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="">
                <!--<button class="btn btn-success" type="submit">BUSCAR</button> <input type="text" name="buscar" id="buscar">-->
                <div class="input-group mb-3 custom-width">
                    <a class="btn btn-success" href="{% url 'nuevo' %}">NUEVO</a>
                    <a class="btn btn-secondary" href="{% url 'buscar' %}" id="button-addon1" >BUSCAR</a>
                    <form  method="POST" action="{% url 'buscar' %}">
                        <!--<button class="btn btn-secondary" type="submit" id="button-addon1">BUSCAR</button>-->
                        {%csrf_token%}
                        {{ form.as_p }}
                        <!--<button class="btn btn-secondary" type="submit" id="button-addon1">BUSCAR</button>
                        <input type="text" class="form-control" placeholder="Ingrese el Item a Buscar" aria-label="Example text with button addon" aria-describedby="button-addon1" name="buscar" id="buscar">-->
                    </form>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <form action="" method="POST">
                <div class="input-group mb-3 custom-width2">
                    <button class="btn btn-secondary" type="submit" id="button-addon2">FILTRO</button>
                    <select name="catNombre" id="id_categoria" class="form-select" id="inputGroupSelect03" aria-label="Example select with button addon">
                        <option selected>Seleccionar la Categoria</option>
                        {% for catnombre in catnombre %}
                        <option value=''></option>
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>
    </div>
    <div class="table-responsive"> 
        <form action="">
            {%csrf_token%}
            <table id="tabla" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr class="encabezados">
                        <th scope="col">ID</th>
                        <th scope="col">CATEG</th>
                        <th scope="col">MARCA</th>
                        <th scope="col">CODIGO</th>
                        <th scope="col">DESCRIPCION</th>
                        <th scope="col">CANTIDAD</th>
                        <th scope="col">P COSTO</th>
                        <th scope="col">UTLIDAD</th>
                        <th scope="col">P VENTA</th>
                        <th scope="col">ACCIONES</th>
                        <!-- Agrega más columnas según las propiedades de tu modelo Producto -->
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                        <tr class="contenido">
                            <td scope="row" class="columNum">{{ producto.id }}</td>
                            <td class="columCategoria">{{ producto.categoria.catNom }}</td>
                            <td class="columMarca">{{ producto.marca.marcaNom }}</td>
                            <td class="columNum">{{ producto.codigo }}</td>
                            <td class="columDescripcion">{{ producto.descripcion }}</td>
                            <td class="columNum">{{ producto.cantidad }}</td>
                            <td class="columMoneda">${{ producto.precioCosto }}</td>
                            <td class="columUtilidad">{{ producto.utilidad.utilDescripcion}}</td>
                            <td class="columMoneda">${{ producto.precioPublico}}</td>
                            <td class="centrarbotones">
                                <div>   
                                    <a class="btn btn-primary btn-sm " href="{% url 'actualizar' id=producto.id %}">EDITAR</a>
                                    <a class="btn btn-danger btn-sm" href="{% url 'eliminar' id=producto.id %}">ELIMINAR</a>
                                </div>
                            </td>
                            <!-- Agrega más celdas según las propiedades de tu modelo Producto -->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
</div>
{% endblock %}